name: test-azure-login

on: [workflow_dispatch]

permissions:
    id-token: write
    contents: read

jobs:
    connect-to-azure:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            path: repo
        - uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_POLICY_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            #subscription-id: ${{ secrets.AZURE_POLICY_SUBSCRIPTION_ID }}
            allow-no-subscriptions: true
            enable-AzPSSession: true
        - name: Azure CLI script
          uses: azure/cli@v2
          with:
              azcliversion: latest
              inlineScript: |
                az account show
        - name: Run Azure PowerShell
          uses: azure/powershell@v2
          with:
            azPSVersion: "latest"
            inlineScript: |
              Get-ExecutionPolicy


        
